### ISSUE TITLE
Mongoose 4.0.2 problem

### ISSUE THREAD

**Issue by ThomWright** [dscook/mean-stack-starter#1]
`mongoose@4.0.2` breaks for me with this issue: Automattic/mongoose#2984 - which is fixed by `4.0.3`.

I'll send a PR in a mo.

**Comment by dscook** [comment]
Thanks for the fix.  Must admit I haven't seen that one before.  I am generally on my Mac so I'm not as close to the Ubuntu instructions as I should be!
