### ISSUE TITLE
How come gulp-ruby-sass instead of gulp-sass?

### ISSUE THREAD

**Issue by ThomWright** [dscook/mean-stack-starter#3]
Using `gulp-sass` instead of `gulp-ruby-sass` could remove the dependency on Ruby and cut down the installation process by three steps:
- Install ruby: `sudo apt-get install ruby`
- Install bundler and sass: `sudo gem install bundler sass`
- Install build dependencies: `bundle install`

Does `gulp-ruby-sass` have some functionality I'm not aware of? If `gulp-sass` could work I'm happy to put a PR together.

BTW I might try dockerising this as an exercise. Hopefully this should make set up nice and quick for anyone with Docker. Thoughts?

**Comment by dscook** [comment]
Some of the build process was taken from the Foundation for Apps starter project and they use the Ruby Sass gem by default.

Libsass with Gulp Sass should work OK, and decrease compilation times, see http://garethcooper.com/2015/02/using-libsass-with-foundation-for-apps/

Up to you if you want to spend the time on this one.  A Docker instance would be very useful, I need to get up to speed on Docker myself!  If you do put one together I'll happily advertise it.
